# -*- coding: utf-8 -*-
{
    "name": "Language Institute Management",
    "version": "17.0.0.0",
    "category": "Industry",
    "summary": "Language school management language institute management language educational management student language school class language institute or school management student language school manage student language institute student language education institute",
    "description": "Language School Management odoo app is designed to provide a comprehensive solution to institutes for managing their operations. With this app, user can easily manage students, teachers, classes, add frequency for classes, add lessons for classes, manage attendance for students, and can generate invoices for class students based on attendance, generate and check report for class, and much more.",
    "author": "BrowseInfo",
    "website": "https://www.browseinfo.com",
    "price": 399,
    "currency": 'EUR',
    "depends": ['hr', 'account'],
    "data": [
        'security/ir.model.access.csv',
        'views/student_view.xml',
        'views/lesson_view.xml',
        'views/attendance_view.xml',
        'views/language_class_view.xml',
        'wizard/add_lesson_wizard_view.xml',
        'report/language_class_report.xml',
        'report/language_class_report_view.xml',
        'views/reporting_view.xml',
    ],
    "auto_install": False,
    "installable": True,
    "live_test_url": 'https://youtu.be/c7gZbIbm4mk',
    "license":"OPL-1",
    "images":['static/description/Language-School-Management.gif'],
}
