{
    'name': 'Whatsapp Odoo for dashboard Integration',
    'version': '17.0.0.1',
    'category': 'Connector',
    'author': 'Pragmatic TechSoft Pvt Ltd.',
    'website': 'pragtech.co.in',
    'summary': 'whatsapp connector whatsapp integration odoo Whatsapp crm Whatsapp lead Whatsapp task Whatsapp sale order Whatsapp purchase order Whatsapp invoice Whatsapp payment reminder Whatsapp pos Whatsapp so Whatsapp point of sale whats app communication',
    'description': """Whatsapp Odoo for dashboard Integration""",
    'depends': ['base', 'contacts', 'delivery', 'crm', 'project', 'sale_management', 'purchase_stock', 'im_livechat', 'website', 'point_of_sale', 'phone_validation','pragtech_conversations_dashboard'],
    'assets': {
        'point_of_sale.assets': [
            'pragtech_whatsapp_messenger/static/src/js/pos_test.js',
        ],
    },
    'data': ['security/ir.model.access.csv',
             'wizard/send_wp_msg_views.xml',
             'views/res_config_settings_view.xml',
             'views/res_partner_views.xml',
            #  'views/template_pos.xml',
             'views/whatsapp_scheduler.xml',
            #  'views/sale_order_view.xml',
             'security/security.xml',
             'security/sale_security.xml',
            #  'views/login_template.xml',
             'views/whatsapp_message_view.xml',
             'views/mail_message_view.xml',
             'views/ir_attachment_view.xml'],
    'qweb': [],
    'license': 'OPL-1',
    'application': True,
    'auto_install': False,
    'installable': True,
}